# Basic
title: iJAYAPRAKASH
subtitle: I'm Just a Myth :) 
avatarTitle: Joshi

avatarDesc: Bonjour/
url: "http://ijayaprakash.in"

# Comment
comment:
    provider: 
    
    short_name: joshi

# Social
social:
    twitter:twitter.com/jaiprince17 
    mail: ijayaprakashjoshi@gmail.com
    
 
# Google Analytics
 Google Analytics:
 id:UA-100696523-2    
 host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}   
    - {title: Label, description: tags, url: '/tags'}   
    - {title: Leave a message, description: liuyan, url: '/Contact'}
    - {title: Resources, description: ziyuan, url: '/Games'}
    - {title: about me, description: about, url: '/about'}

          
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


